use safefood;
CREATE TABLE FOOD
(
    ID BIGINT AUTO_INCREMENT
        PRIMARY KEY,
    SAMPLE_ID VARCHAR(255) NULL,
    FOOD_NAME VARCHAR(255) NULL,
    MAKER VARCHAR(255) NULL,
    INVEST_YEAR VARCHAR(255) NULL,
    CATEGORY VARCHAR(255) NULL,
    DETAIL_CATEGORY VARCHAR(255) NULL,
    FOOD_CODE VARCHAR(255) NULL,
    SOURCE VARCHAR(255) NULL,
    PER_ONCE_GRAM DOUBLE NOT NULL,
    ENERGY_KCAL DOUBLE NOT NULL,
    ENERGY_KJ DOUBLE NOT NULL,
    PROTEIN DOUBLE NOT NULL,
    FAT DOUBLE NOT NULL,
    CARBOHYDRATE DOUBLE NOT NULL,
    TOTAL_SUGAR DOUBLE NOT NULL,
    NATRIUM DOUBLE NOT NULL,
    CHOLESTEROL DOUBLE NOT NULL,
    TOTAL_FATTY_ACID DOUBLE NOT NULL,
    TRANS_FAT DOUBLE NOT NULL
);

